---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint

platforms:
  - name: oraclejdk-ubuntu1604
    groups:
      - oraclejdk
    image: geerlingguy/docker-ubuntu1604-ansible:latest
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    create: ../resources/oraclejdk/create.yml
    prepare: ../resources/oraclejdk/prepare.yml
    destroy: ../resources/oraclejdk/destroy.yml
    converge: ../resources/oraclejdk/playbook.yml
scenario:
  name: ubuntu1604-oraclejdk
verifier:
  name: goss
  lint:
    name: flake8
  directory: ../resources/oraclejdk
