---

- name: Java | Install OpenJDK implementation
  import_tasks: install_openjdk.yml
  when: java_implementation == 'openjdk'
  tags:
    - install

- name: Java | Install OracleJDK implementation using distributed binaries
  import_tasks: install_oraclejdk.yml
  when: java_implementation == 'oraclejdk'
  tags:
    - install
