---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint

platforms:
  - name: openjdk-debian8
    groups:
      - openjdk
    image: geerlingguy/docker-debian8-ansible:latest
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    create: ../resources/openjdk/create.yml
    prepare: ../resources/openjdk/prepare.yml
    destroy: ../resources/openjdk/destroy.yml
    converge: ../resources/openjdk/playbook.yml
scenario:
  name: debian8-openjdk
verifier:
  name: goss
  lint:
    name: flake8
  directory: ../resources/openjdk
