---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint

platforms:
  - name: oraclejdk-debian9
    groups:
      - oraclejdk
    image: geerlingguy/docker-debian9-ansible:latest
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'

  - name: oraclejdk-debian8
    groups:
      - oraclejdk
    image: geerlingguy/docker-debian8-ansible:latest
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'

provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: oracle_jdk
verifier:
  name: goss
  lint:
    name: flake8
